version: '3.9'
services:
  linuxserver:
    image: 'lscr.io/linuxserver/qbittorrent:latest'
    restart: unless-stopped
    volumes:
      - data:/downloads
      - config:/config
    ports:
      - '6881:6881/udp'
      - '6881:6881'
      - '6888:8080'
    environment:
      - WEBUI_PORT=8080
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
    container_name: qbittorrent

volumes:
  data:
    driver: local
  config:
    driver: local