version: '2'
services:
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 7654:8080

  caddy:
    image: abiosoft/caddy:latest
    container_name: caddy
    ports:
      - 2015:2015
      - 2080:80
      - 2443:443
    volumes:
      - $HOME/docker/caddy/Caddyfile:/etc/Caddyfile
      - $HOME/docker/caddy/.caddy:/root/.caddy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $HOME/docker/elasticsearch/data:/usr/share/elasticsearch/data  
    environment:
      discovery.type: single-node  

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - $HOME/docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml  
    
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 4406:3306
    volumes:
      - $HOME/docker/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lovelive

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - $HOME/docker/mysql/data:/var/lib/mysql
      - $HOME/docker/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: lovelive

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 1080:80
      - 1443:443
    volumes:
      - $HOME/docker/nginx/conf.d:/etc/nginx/conf.d
      - $HOME/docker/nginx/html:/usr/share/nginx/html
      - $HOME/docker/nginx/log:/var/log/nginx


  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lovelive

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: pgweb
    ports: 
      - 4400:8081 
    links: 
      - postgres:postgres  
    environment:
      - DATABASE_URL=postgres://postgres:lovelive@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres 
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - $HOME/docker/redis:/data 

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    