version: "3.9"
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: lovelive

volumes:
  data:
    driver: local
  config:
    driver: local