version: "3.9"
services:
  meilisearch:
    image: getmeili/meilisearch:v0.27.1
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: lovelive
    ports:
      - 7700:7700
    volumes:
      - data:/meili_data

volumes:
  data:
    driver: local